# Generated by Django 4.1 on 2022-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FlashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_news_title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('link', models.URLField(null=True)),
                ('upload_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('upload_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('link', models.URLField(null=True)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='Noticeboard')),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
